dataset_type: 'MetaDataset'
dataset_params:
  meta: 'base_classes_val_meta.json'
  rootdir: '/home/user59/data/class_sorted_grayscale/' # Change this to ImageNet directory
transform_params:
  transform_list: ['Scale', 'CenterCrop', 'ToTensor', 'Normalize']
  image_size: 224
  scale: 256
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
data_loader_params:
  batch_size: 256
  shuffle: True
  num_workers: 12
  pin_memory: True
